apiVersion: v1
kind: Service
metadata:
  name: {{ template "busbar.fullname" . }}-web
  labels:
    app: {{ template "busbar.name" . }}
    component: web
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "busbar.name" . }}
    component: web
    release: "{{ .Release.Name }}"
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8000
