apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubeConfig.fullname" . }}
  labels:
    app: {{ template "busbar.name" . }}
    component: {{ template "kubeConfig.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "busbar.name" . }}
    component: {{ template "kubeConfig.fullname" . }}
    release: "{{ .Release.Name }}"
  type: NodePort
  ports:
    - name: kubeconfig
      port: 80
      targetPort: 80
      nodePort: 8001
